### ISSUE TITLE
Support update to running with JDK 11 (LTS)

### ISSUE THREAD

**Issue by GregDomjan** [bsorrentino/maven-confluence-plugin#183]
Testing updating Maven tools to using JDK 11 and got the following issue

```
[INFO] --- confluence-reporting-maven-plugin:5.1.1:deploy (default-cli) @ Project ---
[WARNING] Error injecting: org.bsc.maven.confluence.plugin.ConfluenceDeployMojo
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
    at java.lang.Class.getDeclaredConstructors0 (Native Method)
...
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
```

Found that dependency has been shifted to a separate jar not on the default classpath since JDK9

https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

Addition of maven dependencies allowed to work around 

```
		<plugin>
			<groupId>org.bsc.maven</groupId>
			<artifactId>confluence-reporting-maven-plugin</artifactId>
			<version>5.1.1</version>
			<dependencies>
				<dependency>
					<groupId>javax.xml.bind</groupId>
					<artifactId>jaxb-api</artifactId>
					<version>2.3.0</version>
				</dependency>
				<dependency>
					<groupId>com.sun.xml.bind</groupId>
					<artifactId>jaxb-core</artifactId>
					<version>2.3.0</version>
				</dependency>
				<dependency>
					<groupId>com.sun.xml.bind</groupId>
					<artifactId>jaxb-impl</artifactId>
					<version>2.3.0</version>
				</dependency>
				<dependency>
					<groupId>javax.activation</groupId>
					<artifactId>activation</artifactId>
					<version>1.1.1</version>
				</dependency>
```

**Comment by bsorrentino** [comment]
Hi @GregDomjan thank for feedback

I'll add a profile (activated on jdk version) that will manage this condition

**Comment by bsorrentino** [comment]
I've worked on it and deployed version `6.0-SNAPSHOT` compatible with **jdk11**

@GregDomjan could you test it ?

thanks in advance

**Comment by GregDomjan** [comment]
Using jdk-11.0.1  it worked ok for me.
Thanks @bsorrentino

**Comment by bsorrentino** [comment]
Thank you for support

**Comment by bsorrentino** [comment]
fix released in version `6.0`

**Comment by qwazer** [comment]
HI @bsorrentino  What the reason to add maven plugin prerequisites to support only maven > 3.5.0
https://github.com/bsorrentino/maven-confluence-plugin/blob/master/maven-confluence-reporting-plugin/pom.xml#L10-L12

Unfortunately, in our company, we cannot switch to maven 3.5.0 in near future (at least, in next 6 month) but we want to use the latest version of maven-confluence-plugin. Can we remove maven plugin prerequisite in 6.0.1?

**Comment by qwazer** [comment]
@bsorrentino, yes, absolutely!

**Comment by bsorrentino** [comment]
Hi @qwazer 

I've deployed the version `6.1-SNAPSHOT` not a `6.0.1` as suggested because i've also upgrade maven runtime from 3.0.1 to 3.3.1 in sync with prerequisites

**Comment by qwazer** [comment]
@bsorrentino Thanks a lot!
